### ISSUE TITLE
Refactoring tmt

### ISSUE THREAD

**Issue by thrix** [psss/tmt#1411]
## Refactoring `tmt` before implementing multi-host tests

Before starting to implement multi-host test support, a few areas need refactoring. This issue tracks these work items.

### PRs statuses with dependencies

The following list shows a hierarchy of how PRs depend on each other to show the order in which they should be completed and merged. A higher level means that it should be finished sooner.

Moreover, a review status is provided to know the current state of the PR, maintained by @thrix.

### On review

- #1524
- #1685

### Work items

Please add your name if you start working on it, and link to a pull request once you create it.

- [x] #1378 (@happz's pet peeve) #1524
- [x] #1371 (@idorax was interested)
  - #1725
  - #1776
- [ ] #1082 (@FrNecas)
- [x] #1565 (@happz)
  - #1685

#### Less important items

- [ ] #1373 (@FrNecas PR #1412 )
  - [x] #1540
- [ ] #1372 (@FrNecas)
- [ ] #1599
- [x] #1361 (@janhavlin)
- [ ] #1437 (@thrix)
- [ ] #1438

#### Done \o/

- [x] #1280
- [x] #1384
- [x] #1428
- [x] #1439 
- [x] https://github.com/teemtee/tmt/issues/1560 (@ZelenyMartin)
- [x] #1456 (@ZelenyMartin)
- [x] #1492 (@ZelenyMartin)

**Comment by FrNecas** [comment]
One more to add: https://github.com/teemtee/tmt/issues/1082 (I'll take this one, I just wanted to wait for typing to be done not to ruin everyone's day)

**Comment by psss** [comment]
Multihost support has been implemented a long time ago. Remaining changes related to converting classes to generic type are now tracked under:

* #4145 

Closing.
